version: '3'
services:
    web:
        build: .
        stdin_open: true
        tty: true
        ports: 
            - "8443:8443"
        volumes:
            - "/app/node_modules" 
            - ".:/app"